{{- if or .Values.mariadb.enabled .Values.externalDatabase.host -}}
apiVersion: {{ template "joomla.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "joomla.fullname" . }}
  labels:
    app: {{ template "joomla.fullname" . }}
    chart: {{ template "joomla.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  selector:
    matchLabels:
      app: {{ template "joomla.fullname" . }}
      release: "{{ .Release.Name }}"
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "joomla.fullname" . }}
        chart: {{ template "joomla.chart" . }}
        release: {{ .Release.Name | quote }}
{{- if or .Values.podAnnotations .Values.metrics.enabled }}
      annotations:
  {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
  {{- end }}
  {{- if .Values.metrics.podAnnotations }}
{{ toYaml .Values.metrics.podAnnotations | indent 8 }}
  {{- end }}
{{- end }}
    spec:
{{- include "joomla.imagePullSecrets" . | indent 6 }}
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "status.localhost"
      containers:
      - name: cms-proxyapi
        image: chalonazo/cms-proxyapi:1.2
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: PORT
          value: "4000"
        - name: REACT_APP_TWITTER_CONSUMER_KEY
          value: sAujrbXPzbJgarCvZGxevuvDd
        - name: REACT_APP_TWITTER_CONSUMER_SECRET
          value: EVjZJpm8tzz1439PsjvE2NrPV7gUbpuz6qT6p7ADSASWbXukkC
        - name: REACT_APP_TWITTER_CALLBACK_URL
          value: "https://cms-proxyapi-{{ .Release.Namespace }}.cluster.smartpoke.es/auth/twitter/redirect"
        - name: REACT_APP_FACEBOOK_CLIENT_ID
          value: ""
        - name: REACT_APP_FACEBOOK_CLIENT_SECRET
          value: d315da7da726d5a1c8ecfd48b1a633f1
        - name: REACT_APP_FACEBOOK_CALLBACK_URL
          value: "https://cms-proxyapi-{{ .Release.Namespace }}.cluster.smartpoke.es/auth/facebook/redirect"
        - name: REACT_APP_MONGODB_URI
          value: "mongodb://spring:spring@data-store-mongodb-0.data-store-mongodb-headless.{{ .Release.Namespace }}.svc.cluster.local,data-store-mongodb-1.data-store-mongodb-headless.{{ .Release.Namespace }}.svc.cluster.local,data-store-mongodb-2.data-store-mongodb-headless.{{ .Release.Namespace }}.svc.cluster.local/smartpoke"
        - name: REACT_APP_CLIENT_HOME_PAGE_URL
          value: "https://cms-webui-{{ .Release.Namespace }}.cluster.smartpoke.es"
        ports:
        - containerPort: 4000
      - name: cms-restapi
        image: chalonazo/cms-restapi:1.9
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: API_VERSION
          value: v1
        - name: SERVER
          value: localhost
        - name: PORT
          value: "5000"
        - name: PUBLISH_API
          value: "https://platform-{{ .Release.Namespace }}.cluster.smartpoke.es/directory.php"
        - name: MONGODB_URI
          value: "mongodb://spring:spring@data-store-mongodb-0.data-store-mongodb-headless.{{ .Release.Namespace }}.svc.cluster.local,data-store-mongodb-1.data-store-mongodb-headless.{{ .Release.Namespace }}.svc.cluster.local,data-store-mongodb-2.data-store-mongodb-headless.{{ .Release.Namespace }}.svc.cluster.local/smartpoke"
        - name: WEB_CMS_CORS
          value: "https://cms-webui-{{ .Release.Namespace }}.cluster.smartpoke.es"
        - name: API_CMS_CORS
          value: "https://cms-restapi-{{ .Release.Namespace }}.cluster.smartpoke.es"
        {{- if .Values.mariadb.enabled }}
        - name: MARIADB_HOST
          value: {{ template "joomla.mariadb.fullname" . }}
        - name: MARIADB_PORT
          value: "3306"
        - name: MARIADB_DB
          value: {{ .Values.mariadb.db.name | quote }}
        - name: MARIADB_USER
          value: {{ .Values.mariadb.db.user | quote }}
        - name: MARIADB_PASS
          valueFrom:
            secretKeyRef:
              name: {{ template "joomla.mariadb.fullname" . }}
              key: mariadb-password
        {{- else }}
        - name: MARIADB_HOST
          value: {{ .Values.externalDatabase.host | quote }}
        - name: MARIADB_PORT
          value: {{ .Values.externalDatabase.port | quote }}
        - name: MARIADB_DB
          value: {{ .Values.externalDatabase.database | quote }}
        - name: MARIADB_USER
          value: {{ .Values.externalDatabase.user | quote }}
        - name: MARIADB_PASS
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "externaldb" }}
              key: db-password
        {{- end }}
        ports:
        - containerPort: 5000
      - name: cms-webui
        image: chalonazo/cms-webui:1.26
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: REACT_APP_API_URL
          value: "https://cms-restapi-{{ .Release.Namespace }}.cluster.smartpoke.es/api"
        - name: REACT_APP_PROXY_URL
          value: "https://cms-proxyapi-{{ .Release.Namespace }}.cluster.smartpoke.es"
        - name: REACT_APP_API_ID_FB
          value: ""
        - name: REACT_APP_VERSION_FB
          value: v11.0
        - name: REACT_APP_CLIENT
          value: "99999"
        - name: REACT_APP_API_JOOMLA
          value: "https://platform-{{ .Release.Namespace }}.cluster.smartpoke.es"
        ports:
        - containerPort: 3000
      - name: joomla
        image: {{ template "joomla.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: {{ .Values.allowEmptyPassword | quote }}
        {{- if .Values.mariadb.enabled }}
        - name: MARIADB_HOST
          value: {{ template "joomla.mariadb.fullname" . }}
        - name: MARIADB_PORT_NUMBER
          value: "3306"
        - name: JOOMLA_DATABASE_NAME
          value: {{ .Values.mariadb.db.name | quote }}
        - name: JOOMLA_DATABASE_USER
          value: {{ .Values.mariadb.db.user | quote }}
        - name: JOOMLA_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "joomla.mariadb.fullname" . }}
              key: mariadb-password
        {{- else }}
        - name: MARIADB_HOST
          value: {{ .Values.externalDatabase.host | quote }}
        - name: MARIADB_PORT_NUMBER
          value: {{ .Values.externalDatabase.port | quote }}
        - name: JOOMLA_DATABASE_NAME
          value: {{ .Values.externalDatabase.database | quote }}
        - name: JOOMLA_DATABASE_USER
          value: {{ .Values.externalDatabase.user | quote }}
        - name: JOOMLA_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "externaldb" }}
              key: db-password
        {{- end }}
        - name: JOOMLA_USERNAME
          value: {{ .Values.joomlaUsername | quote }}
        - name: JOOMLA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "joomla.fullname" . }}
              key: joomla-password
        - name: JOOMLA_EMAIL
          value: {{ .Values.joomlaEmail | quote }}
        {{- if .Values.smtpHost }}
        - name: SMTP_HOST
          value: {{ .Values.smtpHost | quote }}
        {{- end }}
        {{- if .Values.smtpPort }}
        - name: SMTP_PORT
          value: {{ .Values.smtpPort | quote }}
        {{- end }}
        {{- if .Values.smtpUser }}
        - name: SMTP_USER
          value: {{ .Values.smtpUser | quote }}
        {{- end }}
        {{- if .Values.smtpPassword }}
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "joomla.fullname" . }}
              key: smtp-password
        {{- end }}
        {{- if .Values.smtpProtocol }}
        - name: SMTP_PROTOCOL
          value: {{ .Values.smtpProtocol | quote }}
        {{- end }}
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /index.php
            port: http
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /index.php
            port: http
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: joomla-data
          mountPath: /bitnami/joomla
{{- if .Values.metrics.enabled }}
      - name: metrics
        image: {{ template "joomla.metrics.image" . }}
        imagePullPolicy: {{ .Values.metrics.image.pullPolicy | quote }}
        command: [ '/bin/apache_exporter', '-scrape_uri', 'http://status.localhost:80/server-status/?auto']
        ports:
        - name: metrics
          containerPort: 9117
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
  {{ toYaml .Values.metrics.resources | indent 10 }}
{{- end }}
      volumes:
      - name: joomla-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "joomla.fullname" . }}-joomla
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end -}}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- end }}
