{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "joomla.fullname" . }}
  labels:
    app: {{ template "joomla.fullname" . }}
    chart: {{ template "joomla.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  annotations:
    {{- if .tls }}
    ingress.kubernetes.io/secure-backends: "true"
    {{- end }}
    {{- if .Values.ingress.certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: "platform-{{ .Release.Namespace }}.cluster.smartpoke.es"
    http:
      paths:
      - path: /
        backend:
          serviceName: "{{ template "joomla.fullname" . }}"
          servicePort: http
  - host: "cms-webui-{{ .Release.Namespace }}.cluster.smartpoke.es"
    http:
      paths:
        - path: /
          backend:
            serviceName: "{{ template "joomla.fullname" . }}-cms-webui"
            servicePort: http
  - host: "cms-proxyapi-{{ .Release.Namespace }}.cluster.smartpoke.es"
    http:
      paths:
        - path: /
          backend:
            serviceName: "{{ template "joomla.fullname" . }}-cms-proxyapi"
            servicePort: http
  - host: "cms-restapi-{{ .Release.Namespace }}.cluster.smartpoke.es"
    http:
      paths:
        - path: /
          backend:
            serviceName: "{{ template "joomla.fullname" . }}-cms-restapi"
            servicePort: http
  tls:
    - hosts:
        - "platform-{{ .Release.Namespace }}.cluster.smartpoke.es"
        - "cms-webui-{{ .Release.Namespace }}.cluster.smartpoke.es"
        - "cms-proxyapi-{{ .Release.Namespace }}.cluster.smartpoke.es"
        - "cms-restapi-{{ .Release.Namespace }}.cluster.smartpoke.es"
      secretName: "{{ .Release.Namespace }}-cluster-smartpoke-tls"
{{- end }}
