{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "joomla.fullname" . }}
  labels:
    app: {{ template "joomla.fullname" . }}
    chart: {{ template "joomla.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  annotations:
    {{- if .tls }}
    ingress.kubernetes.io/secure-backends: "true"
    {{- end }}
    {{- if .Values.ingress.certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: "platform-{{ .Release.Namespace }}.cluster.smartpoke.es"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: "{{ template "joomla.fullname" . }}"
            port:
              name: http
  - host: "cms-webui-{{ .Release.Namespace }}.cluster.smartpoke.es"
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: "{{ template "joomla.fullname" . }}-cms-webui"
              port:
                name: http
  - host: "cms-proxyapi-{{ .Release.Namespace }}.cluster.smartpoke.es"
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: "{{ template "joomla.fullname" . }}-cms-proxyapi"
              port:
                name: http
  - host: "cms-restapi-{{ .Release.Namespace }}.cluster.smartpoke.es"
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: "{{ template "joomla.fullname" . }}-cms-restapi"
              port:
                name: http
  tls:
    - hosts:
        - "platform-{{ .Release.Namespace }}.cluster.smartpoke.es"
        - "cms-webui-{{ .Release.Namespace }}.cluster.smartpoke.es"
        - "cms-proxyapi-{{ .Release.Namespace }}.cluster.smartpoke.es"
        - "cms-restapi-{{ .Release.Namespace }}.cluster.smartpoke.es"
      secretName: "{{ .Release.Namespace }}-cluster-smartpoke-tls"
{{- end }}
