apiVersion: v1
kind: Service
metadata:
  name: "{{ template "joomla.fullname" . }}-cms-proxyapi"
  labels:
    app: {{ template "joomla.fullname" . }}
    chart: {{ template "joomla.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: {{ template "joomla.fullname" . }}